---
title: "Exploratory analysis: gender and cognitive competence"
format: html
editor: visual
---

```{r}
# packages
library(dplyr)
library(readr)
```

```{r}
# data
allYrsFinal <- read_csv("FinalFiles2023/Data/All Years Final Public - with Vars.csv")
```

```{r}
#cognitive.competence.pre	cognitive.competence.post
#cognitive.competence.change	
# gender
allYrsFinal|>
  filter(!is.na(gender), !is.na(cognitive.competence.pre)) |>
  ggplot(aes(x=gender, y=cognitive.competence.pre)) + 
  geom_boxplot()
```

```{r}
t.test(allYrsFinal$cognitive.competence.pre ~ allYrsFinal$gender)
```

```{r}
allYrsFinal|>
  filter(!is.na(gender), !is.na(cognitive.competence.post)) |>
  ggplot(aes(x=gender, y=cognitive.competence.post)) + 
  geom_boxplot()
```

```{r}
t.test(allYrsFinal$cognitive.competence.post ~ allYrsFinal$gender)
```

```{r}
allYrsFinal|>
  filter(!is.na(gender), !is.na(cognitive.competence.change)) |>
  ggplot(aes(x=gender, y=cognitive.competence.change)) + 
  geom_boxplot()
```

```{r}
t.test(allYrsFinal$cognitive.competence.change ~ allYrsFinal$gender)
```




```{r}
# Define the patterns to search for
competence <- c("^q6e", "^q7a", "^q8f", "^q9a", "^q9b", "^q9e")

# Initialize an empty list to store the t-test results
t_test_results <- list()

# Loop through each pattern
for (pattern in competence) {
  # Find the column names that match the pattern
  matched_columns <- grep(pattern, colnames(allYrsFinal), value = TRUE)
  
  # Loop through each matched column and perform a t-test
  for (column in matched_columns) {
    # Perform the t-test
    t_test_result <- t.test(allYrsFinal[[column]] ~ allYrsFinal$gender)
    
    # Store the result in the list with the column name as the key
    t_test_results[[column]] <- t_test_result
  }
}
t_test_results

```

```{r}

# Initialize an empty list to store the t-test results
wilcox_results <- list()

# Loop through each pattern
for (pattern in competence) {
  # Find the column names that match the pattern
  matched_columns <- grep(pattern, colnames(allYrsFinal), value = TRUE)
  
  # Loop through each matched column and perform a t-test
  for (column in matched_columns) {
    # Perform the t-test
    wilcox_result <- wilcox.test(allYrsFinal[[column]] ~ allYrsFinal$gender)
    
    # Store the result in the list with the column name as the key
    wilcox_results[[column]] <- wilcox_result
  }
}
wilcox_results

```
